spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: TABIHOUDAI
    password: TABIHOUDAI

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: oracle

server:
  port: 8081

#org:
#  postImage:
#    upload:
#      path: E:\upload
