
# key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1523:xe
    username: login_test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: oracle
