# key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1523:xe
    username: login_test
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: oracle

    servlet:
      multipart:
        enabled: true
        location: C:\Users\cksdu\Desktop\프로젝트 코드\profile
        max-request-size: 30MB
        max-file-size: 10MB

com:
  tabihoudai:
    upload:
      path: C:\Users\cksdu\Desktop\프로젝트 코드\profile

exchange:
  api:
    url: https://www.koreaexim.go.kr/site/program/financial/exchangeJSON
    key: fHYdsH7k0BLIjnVidfS6YTldWI0fMDcy
    data: AP01

